application: likeindex
version: 1
runtime: python
api_version: 1

handlers:
- url: /example
  script: example.py
  secure: optional

- url: .*
  script: likeindex.py
  secure: optional

builtins:
- datastore_admin: on
- appstats: on
